version: '2'
services:
  mapas:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: /var/www/dev/start.sh
    ports:
      - "80:80"
    volumes:
      - ./.env:/.env
      - ./docker/production/php.ini:/usr/local/etc/php/php.ini

      # scripts principais
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./docker/jobs-cron.sh:/jobs-cron.sh
      - ./docker/recreate-pending-pcache-cron.sh:/recreate-pending-pcache-cron.sh

      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock

      - ./config:/var/www/config
      - ./public:/var/www/html
      - ./scripts:/var/www/scripts
      - ./src:/var/www/src
      - ./var:/var/www/var

#     - ./docker/development/router.php:/var/www/router.php

#     - ./config.d:/var/www/config/config.d

      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/var/private-files

    links:
      - redis
      - sessions

    environment:
      - BUILD_ASSETS=1

      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379

    depends_on:
      - redis
      - sessions

    stdin_open: true
    tty: true

  redis:
    image: redis:6
    command: --maxmemory 1024Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  sessions:
    image: redis:6
    restart: unless-stopped
    command: --maxmemory 512Mb --maxmemory-policy allkeys-lru
    volumes:
      - ./docker-data/sessions:/data
