<?php

use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Opportunity',
        ),
        'restricted_terms' => array(
            i::__('Acervos Públicos ou de Interesse Público'),
            i::__('Animação'),
            i::__('Antropologia'),
            i::__('Áreas técnicas da cultura'),
            i::__('Arqueologia'),
            i::__('Arquitetura e Urbanismo'),
            i::__('Arquivo'),
            i::__('Arte-Educação'),
            i::__('Artes Cênicas'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Arte Gráfica'),
            i::__('Arte Santeira'),
            i::__('Artes Clássicas'),
            i::__('Artes do Espetáculo'),
            i::__('Artes Integradas'),
            i::__('Artes Visuais'),
            i::__('Artesanato'),
            i::__('Audiovisual'),
            i::__('Bandas de Congo e Ticumbi'),
            i::__('Bibliotecas'),
            i::__('Caboclinho'),
            i::__('Canto Coral'),
            i::__('Capoeira'),
            i::__('Carimbó'),
            i::__('Centros de Memória'),
            i::__('Carnaval'),
            i::__('Cavalo Marinho'),
            i::__('Cinema'),
            i::__('Ciranda'),
            i::__('Circo'),
            i::__('Congado'),
            i::__('Conservação e Restauro'),
            i::__('Construção Civil Tradicional'),
            i::__('Cultura Afro-Brasileira'),
            i::__('Cultura Alimentar'),
            i::__('Cultura Cigana'),
            i::__('Cultura DEF'),
            i::__('Cultura Digital'),
            i::__('Cultura e Comunicação'),
            i::__('Cultura e Direitos Humanos'),
            i::__('Cultura e Educação'),
            i::__('Cultura e Esporte'),
            i::__('Cultura e Meio Ambiente'),
            i::__('Cultura e Saúde'),
            i::__('Cultura LGBTQIAPN+'),
            i::__('Cultura Negra'),
            i::__('Cultura Urbana'),
            i::__('Cultura Hip-Hop e Funk'),
            i::__('Cultura, Infância e Adolescência'),
            i::__('Culturas dos Povos de Comunidades Tradicionais de Matriz Africana'),
            i::__('Culturas dos Povos Indígenas'),
            i::__('Culturas dos Povos Nômades'),
            i::__('Culturas Estrangeiras'),
            i::__('Culturas Populares e Tradicionais'),
            i::__('Culturas de Povos de Terreiros'),
            i::__('Culturas Quilombolas'),
            i::__('Dança'),
            i::__('Dança de Salão'),
            i::__('Desenho Industrial'),
            i::__('Design de Moda'),
            i::__('Design Gráfico'),
            i::__('Design de Interiores'),
            i::__('Design Paisagístico'),
            i::__('Direito Autoral'),
            i::__('Escultura'),
            i::__('Economia Criativa'),
            i::__('Economia da Cultura'),
            i::__('Tradição Oral e Falares'),
            i::__('Festas Populares'),
            i::__('Festejos Juninos'),
            i::__('Feiras e Exposições'),
            i::__('Filologia'),
            i::__('Filosofia'),
            i::__('Forró'),
            i::__('Fotografia'),
            i::__('Gastronomia'),
            i::__('Gestão Cultural'),
            i::__('Grafite'),
            i::__('Gravura'),
            i::__('História e Cultura'),
            i::__('Humor'),
            i::__('Intercâmbio Cultural'),
            i::__('Internet Podcasting'),
            i::__('Jogos Eletrônicos'),
            i::__('Jongo'),
            i::__('Jornais e Revistas'),
            i::__('Jornalismo e Cultura'),
            i::__('Leitura'),
            i::__('Lidas Campeiras'),
            i::__('Linguagem'),
            i::__('Línguas'),
            i::__('Literatura'),
            i::__('Livro'),
            i::__('Manifestações Artísticas Culturais Afro-Brasileiras'),
            i::__('Maracatu'),
            i::__('Memória'),
            i::__('Mídias Sociais e Mídias Interativas'),
            i::__('Mídias Livres'),
            i::__('Mímica'),
            i::__('Moda'),
            i::__('Museu'),
            i::__('Museologia'),
            i::__('Música'),
            i::__('Música Erudita'),
            i::__('Música Instrumental'),
            i::__('Música Popular'),
            i::__('Novas Mídias'),
            i::__('Ópera'),
            i::__('Ourivesaria'),
            i::__('Paisagens culturais'),
            i::__('Paradista'),
            i::__('Patrimônio Cultural Imaterial'),
            i::__('Patrimônio Cultural Material'),
            i::__('Patrimônio Natural'),
            i::__('Performance'),
            i::__('Pesca Artesanal'),
            i::__('Pesquisa em Cultura'),
            i::__('Pesquisa & Desenvolvimento (P&D)'),
            i::__('Pintura'),
            i::__('Pintura Corporal'),
            i::__('Produção Cultural'),
            i::__('Produção de Doces Tradicionais'),
            i::__('Produção de Eventos'),
            i::__('Quadrilha Junina'),
            i::__('Rádio'),
            i::__('Reisado'),
            i::__('Sítios Históricos e Arqueológicos'),
            i::__('Serviços Criativos'),
            i::__('Sociologia'),
            i::__('Tambor de Crioula'),
            i::__('Teatro'),
            i::__('Tecnologias Culturais'),
            i::__('Televisão'),
            i::__('Tradições'),
            i::__('Turismo e Cultura'),
            i::__('Vídeo'),
            i::__('Xondaro'),
            i::__('Outra'),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Linguagem'),
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Artes Integradas'),
            i::__('Artes Visuais'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Cultura Digital'),
            i::__('Culturas dos Povos Indígenas'),
            i::__('Cultura Tradicional'),
            i::__('Curso ou Oficina'),
            i::__('Dança'),
            i::__('Exposição'),
            i::__('Hip Hop'),
            i::__('Livro e Literatura'),
            i::__('Música Popular'),
            i::__('Música Erudita'),
            i::__('Palestra, Debate ou Encontro'),
            i::__('Rádio'),
            i::__('Teatro'),
            i::__('Outros')
        )
    ),
    4 => array(
        'slug' => 'funcao',
        'description' => i::__('Função'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__("Aderecista"),
            i::__("Adestrador(a) para Artes Cênicas"),
            i::__("Afinador de Instrumentos"),
            i::__("Ajudante de Câmera"),
            i::__("Ajudante de Locação"),
            i::__("Ajudante de Objetos"),
            i::__("Ajudante de Produção"),
            i::__("Amestrador(a)"),
            i::__("Aplicador(a) de sign"),
            i::__("Armeiro(a)"),
            i::__("Assessor(a) de Comunicação"),
            i::__("Assistente Administrativo"),
            i::__("Assistente de Arte"),
            i::__("Assistente de Artista Gráfico"),
            i::__("Assistente de Backstage"),
            i::__("Assistente de Camarim"),
            i::__("Assistente de Câmera"),
            i::__("Assistente de Cenotécnica"),
            i::__("Assistente de Continuidade"),
            i::__("Assistente de Controller"),
            i::__("Assistente de Criação Artística"),
            i::__("Assistente de Edição"),
            i::__("Assistente de Edição de Som"),
            i::__("Assistente de Eletricista"),
            i::__("Assistente de Figurino"),
            i::__("Assistente de Ilha de Edição"),
            i::__("Assistente de Maquiagem"),
            i::__("Assistente de Maquinaria"),
            i::__("Assistente de Montagem"),
            i::__("Assistente de Objetos"),
            i::__("Assistente de Pós Produção"),
            i::__("Assistente de Produção (Base ou Set"),
            i::__("Assistente de Produção de Arte"),
            i::__("Assistente de Produção de Elenco"),
            i::__("Assistente de Produção de Locação"),
            i::__("Assistente de Produção em geral"),
            i::__("Assistente de Produção Musical"),
            i::__("Assistente de Roteiro"),
            i::__("Assistente de Som"),
            i::__("Assistente de Transporte"),
            i::__("Assistente Mixador(a)"),
            i::__("Audiodescritor(a)"),
            i::__("Barreira"),
            i::__("Bilheteiro(a)"),
            i::__("Bordadeiro(a)"),
            i::__("Cabeleireiro"),
            i::__("Cabeleireiro(a)"),
            i::__("Camareiro(a)"),
            i::__("Capataz(a) - Montador(a)"),
            i::__("Carpinteiro(a)"),
            i::__("Cenógrafo(a)"),
            i::__("Cenotécnico(a)"),
            i::__("Chefe de Maquinária"),
            i::__("Cinegrafista"),
            i::__("Colorista"),
            i::__("Colorista Assistente"),
            i::__("Consultor de Imagem"),
            i::__("Consultor em Legendagem"),
            i::__("Consultor(a) em Audiodescrição"),
            i::__("Consultor(a) em Braille"),
            i::__("Consultor(a) em Libras"),
            i::__("Continuista"),
            i::__("Contrarregra"),
            i::__("Coolhunter"),
            i::__("Coordenador(a) de Palco"),
            i::__("Cortineiro(a)"),
            i::__("Costureiro(a)"),
            i::__("Design de Montagem"),
            i::__("Diagramador(a)"),
            i::__("Digitalizador(a)"),
            i::__("Diretor(a) de Palco"),
            i::__("Editor de Partituras"),
            i::__("Editor(a)"),
            i::__("Editor(a) de Som"),
            i::__("Eletricista"),
            i::__("Eletricista Chefe"),
            i::__("Engenheiro(a) de Som"),
            i::__("Ensaiador(a)"),
            i::__("Estampador"),
            i::__("Figurinista"),
            i::__("Foley"),
            i::__("Guia-intérprete de língua de sinais"),
            i::__("Iluminador"),
            i::__("Iluminador(a)"),
            i::__("Legendista ou Tradutor(a)"),
            i::__("Logger"),
            i::__("Luthier"),
            i::__("Maquiador"),
            i::__("Maquiador(a)"),
            i::__("Maquinista"),
            i::__("Marcador(a) de Cena"),
            i::__("Mediador(a)"),
            i::__("Mestre(a) de Pista"),
            i::__("Montador(a)"),
            i::__("Montador(a) de Palco"),
            i::__("Motorista de Audiovisual"),
            i::__("Músico-Musicista"),
            i::__("Operador(a) de Luz"),
            i::__("Operador(a) de Som"),
            i::__("Outra função técnica"),
            i::__("Passador (a)"),
            i::__("Peruqueiro"),
            i::__("Peruqueiro(a)"),
            i::__("Pilotista"),
            i::__("Produtor de Casting"),
            i::__("Produtor(a) de Casting/Booker"),
            i::__("Produtor(a) Fonográfico"),
            i::__("Radialista"),
            i::__("Roadie"),
            i::__("Sapateiro"),
            i::__("Secretario(a) de Frente"),
            i::__("Secretário(a) Teatral"),
            i::__("Serigrafista"),
            i::__("Sonoplasta"),
            i::__("Tatuador"),
            i::__("Técnico de Luz"),
            i::__("Técnico(a) Contábil"),
            i::__("Técnico(a) de Estúdio"),
            i::__("Técnico(a) de Luz"),
            i::__("Técnico(a) de Palco"),
            i::__("Técnico(a) de Som"),
            i::__("Técnico(a) de Som Direto"),
            i::__("Tradutor(a) ou Intérprete de Libras"),
            i::__("Transcritor ou Revisor em Braille"),
            i::__("Visagista"),
            i::__("Visual Merchandiser"),
            i::__("Vitrinista"),
        )
    )
);
